-- require("gruvbox").setup({
--     terminal_colors = true, -- add neovim terminal colors
--     undercurl = true,
--     underline = true,
--     bold = true,
--     italic = {
--       strings = false,
--       emphasis = false,
--       comments = false,
--       operators = false,
--       folds = false,
--     },
--     strikethrough = true,
--     invert_selection = false,
--     invert_signs = false,
--     invert_tabline = false,
--     invert_intend_guides = false,
--     inverse = true, -- invert background for search, diffs, statuslines and errors
--     contrast = "", -- can be "hard", "soft" or empty string
--     palette_overrides = {},
--     overrides = {},
--     dim_inactive = false,
--     transparent_mode = false,
--   })
--   vim.cmd("colorscheme gruvbox")


-- changetheme3

-- require("tokyonight").setup({
--   -- use the night style
--   style = "night",
--   -- disable italic for functions
--   styles = {
--     functions = {}
--     variables = {},
--     comments = { italic = false },
--     keywords = { italic = false },
--   }
-- })
-- vim.cmd[[colorscheme tokyonight]]